### ISSUE TITLE
Brightness after stop is not the same as settings.

### ISSUE THREAD

**Issue by LithiumNL** [mochman/node-red-contrib-light-transition#8]
After firing the node the first time everything works like a charm. When sending a stop command and a new start command the brightness has not been reset to the initial values. The color_temp instead is working correctly.

![afbeelding](https://user-images.githubusercontent.com/4047993/147607138-02528969-36e4-43eb-97ca-d55ba0508bc7.png)

There is no information passed trough via previous nodes. The payload has only the string text off (the node before checks if the lights are off).
If i move the light transition node around and press the save button (only changed nodes save) everything is working correctly, until one time. After that it start over like above.

![afbeelding](https://user-images.githubusercontent.com/4047993/147607995-b498da6b-271d-49fc-bc55-530b462fe29b.png)
![afbeelding](https://user-images.githubusercontent.com/4047993/147608020-ac430375-ccee-4f2f-8fbb-b2db5ce8a591.png)

**Comment by mochman** [comment]
I will take a look, thanks.

**Comment by mochman** [comment]
I published a new version (1.4.2) to flows.nodered.org.  This should fix the issue as well as an underlying problem with not resetting any of the data when stopped.

**Comment by LithiumNL** [comment]
Thanks for your fast response. I will test the new version and send you some feedback when the issue is still there.
